[project]
name = "trans-box"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.55.3",
    "polib>=1.2.0",
    "rich>=13.9.4",
    "tqdm>=4.67.1",
]
